swagger: '2.0'
info:
  title: Course Management API
  version: '1.0'
paths:
  /auth/register:
    post:
      summary: Register a new user
      parameters:
        - name: body
          in: body
          description: User information
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '201':
          description: User registered successfully
        '500':
          description: Error registering user
  /auth/login:
    post:
      summary: Login an existing user
      parameters:
        - name: body
          in: body
          description: User credentials
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Invalid username or password
        '500':
          description: Error logging in
  /api/courses:
    post:
      summary: Create a new course
      parameters:
        - name: body
          in: body
          description: Course information
          required: true
          schema:
            $ref: '#/definitions/CourseInput'
      responses:
        '201':
          description: Course created successfully
        '500':
          description: Error creating course
    get:
      summary: Get all courses
      responses:
        '200':
          description: List of courses
          schema:
            type: array
            items:
              $ref: '#/definitions/Course'
        '500':
          description: Error retrieving courses
  /api/courses/{id}:
    get:
      summary: Get a course by ID
      parameters:
        - name: id
          in: path
          description: ID of the course to retrieve
          required: true
          type: integer
      responses:
        '200':
          description: Course details
          schema:
            $ref: '#/definitions/Course'
        '404':
          description: Course not found
        '500':
          description: Error retrieving course by ID
    put:
      summary: Update a course by ID
      parameters:
        - name: id
          in: path
          description: ID of the course to update
          required: true
          type: integer
        - name: body
          in: body
          description: Course information to update
          required: true
          schema:
            $ref: '#/definitions/CourseInput'
      responses:
        '200':
          description: Course updated successfully
        '500':
          description: Error updating course
    delete:
      summary: Delete a course by ID
      parameters:
        - name: id
          in: path
          description: ID of the course to delete
          required: true
          type: integer
      responses:
        '200':
          description: Course deleted successfully
        '500':
          description: Error deleting course

definitions:
  CourseInput:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      instructor:
        type: string
      price:
        type: number
  Course:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      description:
        type: string
      instructor:
        type: string
      price:
        type: number
